version: "3.3"
services:
  modbus4mqtt:
    image: tjhowse/modbus4mqtt
    container_name: modbus4mqtt-bartlwp
    command: >
      --hostname "$MQTT_SERVER_ADDRESS"
      --port "$MQTT_SERVER_PORT"
      --username "$MQTT_SERVER_USER"
      --password "$MQTT_SERVER_PASSWORD"
      --config /modbus4mqtt/config.yml
      --mqtt_topic_prefix "$MODBUS4MQTT_TOPIC_PREFIX"
    restart: unless-stopped
    volumes:
      - $MODBUS4MQTT_CONFIG:/modbus4mqtt/config.yml
    env_file:
      - .env

  ha-discovery:
    build:
      context: .
      dockerfile: Dockerfile.discovery
    container_name: ha-discovery-bartlwp
    restart: "no" # Run once at startup
    environment:
      - CONFIG_FILE=/modbus4mqtt/config.yml
      - MQTT_PREFIX=$MODBUS4MQTT_TOPIC_PREFIX
      - DISCOVERY_PREFIX=${DISCOVERY_PREFIX:-homeassistant}
      - OUTPUT_FILE=/tmp/ha_discovery.json
    volumes:
      - $MODBUS4MQTT_CONFIG:/modbus4mqtt/config.yml
    env_file:
      - .env
    depends_on:
      - modbus4mqtt

  telegraf:
    image: telegraf
    hostname: telegraf-mqtt-bartlwp
    container_name: telegraf-mqtt-bartlwp
    volumes:
      # Mount for telegraf configuration
      - ./config/telegraf/:/etc/telegraf/
      # Mount for Docker API access
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    depends_on:
      - modbus4mqtt
    restart: unless-stopped
