version: "3.3"
services:
  modbus4mqtt:
    image: tjhowse/modbus4mqtt
    container_name: modbus4mqtt-bartlwp
    command: >
      --hostname "$MQTT_SERVER_ADDRESS"
      --port "$MQTT_SERVER_PORT"
      --username "$MQTT_SERVER_USER"
      --password "$MQTT_SERVER_PASSWORD"
      --config /modbus4mqtt/config.yml
      --mqtt_topic_prefix bartl_wp
    restart: unless-stopped
    volumes:
      - ./config/modbus4mqtt/Bartl-WP.yml:/modbus4mqtt/config.yml

  telegraf:
    image: telegraf
    hostname: telegraf-mqtt-bartlwp
    container_name: telegraf-mqtt-bartlwp
    volumes:
       # Mount for telegraf configuration
      - ./config/telegraf/:/etc/telegraf/
      # Mount for Docker API access
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    depends_on:
      - modbus4mqtt

