ip: 192.168.1.211
port: 502
update_rate: 5
address_offset: 0
#variant: BartlWP
scan_batching: 1
registers:
  - pub_topic:  bartl_wp/heizkreis/raumtemperatur/AKTUELL
    address: 1
    # description : AKTUELLE_RAUMTEMPERATUR
    scale: 0.1
    # unit: °C
  - pub_topic:  bartl_wp/heizkreis/raumtemperatur/AKTUELLER_SOLLWERT_INKLUSIVE_OFFSET
    address: 2
    # description : AKTUELLER_RAUMSOLLWERT_INKLUSIVE_RAUMSOLLWERT_OFFSET
    scale: 0.1
    # unit: °C
  - pub_topic:  bartl_wp/heizkreis/raumtemperatur/AKTUELL_GUELTIGE
    address: 3
    # description : AKTUELL_GUELTIGE_RAUMTEMPERATUR
    scale: 0.1
    # type: R
    # unit: °C
  - pub_topic:  bartl_wp/heizkreis/raumtemperatur/heizbetrieb/NORMAL
    set_topic:  bartl_wp/heizkreis/raumtemperatur/heizbetrieb/NORMAL/set
    address: 4
    # description : NORMAL_RAUMTEMPERATUR_HEIZBETRIEB
    scale: 0.1
    # type: R/W
    # unit: °C
  - pub_topic:  bartl_wp/heizkreis/raumtemperatur/heizbetrieb/NACHTABSENKUNG
    set_topic:  bartl_wp/heizkreis/raumtemperatur/heizbetrieb/NACHTABSENKUNG/set
    address: 5
    # description : NACHTABSENK_RAUMTEMPERATUR_HEIZBETRIEB
    scale: 0.1
    # type: R/W
    # unit: °C
  - pub_topic:  bartl_wp/heizkreis/raumtemperatur/OFFSET
    set_topic:  bartl_wp/heizkreis/raumtemperatur/OFFSET/set
    address: 6
    # description : OFFSET_DER_AKTUELL_GUELTIGEN_RAUMTEMPERATUR
    scale: 0.1
    # type: R/W
    # unit: °C
  - pub_topic:  bartl_wp/heizkreis/BETRIEBSART
    set_topic:  bartl_wp/heizkreis/BETRIEBSART/set
    address: 7
    # description : BETRIEBSART_HEIZKREIS
    # type: R/W
    value_map:
      Standby: 0
      Uhrenprogramm: 1
      Tag: 2
      Nacht: 3
      Urlaub: 4
      Party: 5
  - pub_topic:  bartl_wp/heizkreis/raumtemperatur/kuehlbetrieb/NORMAL
    set_topic:  bartl_wp/heizkreis/raumtemperatur/kuehlbetrieb/NORMAL/set
    address: 8
    # description : NORMAL_RAUMTEMPERATUR_KUEHLBETRIEB
    scale: 0.1
    # type: R/W
    # unit: °C
  - pub_topic:  bartl_wp/heizkreis/raumtemperatur/kuehlbetrieb/NACHTABSENKUNG
    set_topic:  bartl_wp/heizkreis/raumtemperatur/kuehlbetrieb/NACHTABSENKUNG/set
    address: 9
    # description : NACHTABSENK_RAUMTEMPERATUR_KUEHLBETRIEB
    scale: 0.1
    # type: R/W
    # unit: °C
  - pub_topic:  bartl_wp/heizkreis/AKTUELLE_RAUMFEUCHTE_PROZENT
    address: 10
    # desc_PROZENTription : AKTUELLE_RAUMFEUCHTE
    # type: R
    # unit: '%'
  - pub_topic:  bartl_wp/heizkreis/betriebsmodus/KUEHLEN_BEI_EXTERNER_ANSTEUERUNG
    set_topic:  bartl_wp/heizkreis/betriebsmodus/KUEHLEN_BEI_EXTERNER_ANSTEUERUNG/set
    address: 11
    # description : BETRIEBSMODUS_KUEHLEN_BEI_EXTERNER_ANSTEUERUNG
    # type: R/W
    # unit: null
  - pub_topic:  bartl_wp/heizkreis/betriebsmodus/HEIZEN_BEI_EXTERNER_ANSTEUERUNG
    set_topic:  bartl_wp/heizkreis/betriebsmodus/HEIZEN_BEI_EXTERNER_ANSTEUERUNG/set
    address: 12
    # description : BETRIEBSMODUS_HEIZEN_BEI_EXTERNER_ANSTEUERUNG
    # type: R/W
    # unit: null
  - pub_topic:  bartl_wp/heizkreis/temperatur/vorlauf/SOLLWERT_BEI_EXTERNER_ANSTEUERUNG
    set_topic:  bartl_wp/heizkreis/temperatur/vorlauf/SOLLWERT_BEI_EXTERNER_ANSTEUERUNG/set
    address: 13
    # description : VORLAUFSOLLWERT_BEI_EXTERNER_ANSTEUERUNG
    scale: 0.1
    # type: R/W
    # unit: °C
  - pub_topic:  bartl_wp/heizkreis/temperatur/vorlauf/ISTWERT
    address: 14
    # description : HEIZKREIS_VORLAUF_ISTWERT
    scale: 0.1
    # type: R
    # unit: °C
  - pub_topic:  bartl_wp/heizkreis/PUMPE
    set_topic:  bartl_wp/heizkreis/PUMPE/set
    address: 15
    # description : HEIZKREISPUMPE
    # type: R
    # unit: null
  - pub_topic:  bartl_wp/heizkreis/temperatur/ruecklauf/ISTWERT
    address: 16
    # description : HEIZKREIS_RUECKLAUF_ISTWERT
    scale: 0.1
    # type: R
    # unit: °C
  - pub_topic:  bartl_wp/heizkreis/AKTUELLE_ANFORDERUNG1
    address: 17
    # description : AKTUELLE_ANFORDERUNG
    # type: R
    value_map:
      AUS: 0
      AKTIV: 1
      Temp-/Prio AUS: 3
      AT_AUS: 5
  - pub_topic:  bartl_wp/heizkreis/AKTUELLE_ANFORDERUNG2
    address: 18
    # description : AKTUELLE_ANFORDERUNG
    # type: R
    value_map:
      AUS: 0
      AKTIV: 1
      Temp-/Prio AUS: 3
      AT_AUS: 5
  - pub_topic:  bartl_wp/heizkreis/temperatur/AUSSEN_GEFILTERT
    address: 19
    # description : GEFILTERTE_AUSSENTMPERATUR
    scale: 0.1
    # type: R
    # unit: °C
  - pub_topic:  bartl_wp/heizkreis/temperatur/heizgrenze/TAG_BETRIEB
    set_topic:  bartl_wp/heizkreis/temperatur/heizgrenze/TAG_BETRIEB/set
    address: 20
    # description : HEIZGRENZE_TAG_BETRIEB
    scale: 0.1
    # type: R/W
    # unit: °C
  - pub_topic:  bartl_wp/heizkreis/temperatur/heizgrenze/NACHT_BETRIEB
    set_topic:  bartl_wp/heizkreis/temperatur/heizgrenze/NACHT_BETRIEB/set
    address: 21
    # description : HEIZGRENZE_NACHT_BETRIEB
    scale: 0.1
    # type: R/W
    # unit: °C
  - pub_topic:  bartl_wp/heizkreis/temperatur/kuehlgrenze/TAG_BETRIEB
    set_topic:  bartl_wp/heizkreis/temperatur/kuehlgrenze/TAG_BETRIEB/set
    address: 22
    # description : KUEHLGRENZE_TAG_BETRIEB
    scale: 0.1
    # type: R/W
    # unit: °C
  - pub_topic:  bartl_wp/heizkreis/temperatur/kuehlgrenze/NACHT_BETRIEB
    set_topic:  bartl_wp/heizkreis/temperatur/kuehlgrenze/NACHT_BETRIEB/set
    address: 23
    # description : KUEHLGRENZE_NACHT_BETRIEB
    scale: 0.1
    # type: R/W
    # unit: °C
  - pub_topic:  bartl_wp/heizkreis/temperatur/vorlauf/MAXIMAL
    set_topic:  bartl_wp/heizkreis/temperatur/vorlauf/MAXIMAL/set
    address: 24
    # description : VORLAUF_MAXIMAL
    scale: 0.1
    # type: R/W
    # unit: °C
  - pub_topic:  bartl_wp/heizkreis/temperatur/vorlauf/MINIMAL
    set_topic:  bartl_wp/heizkreis/temperatur/vorlauf/MINIMAL/set
    address: 25
    # description : VORLAUF_MINIMAL
    scale: 0.1
    # type: R/W
    # unit: °C
  - pub_topic:  bartl_wp/heizkreis/sollspreizung_vl_rl/AKTUELL
    address: 26
    # description : AKTUELL_GUELTIGE_VL_RL_SOLLSPREIZUNG
    scale: 0.1
    # type: R
    # unit: null
  - pub_topic:  bartl_wp/heizkreis/SOLLDREHZAHL_PUMPE_PERCENT
    address: 27
    # description : PUMPEN_SOLLDREHZAHL
    # type: R
    # unit: '%'
  - pub_topic:  bartl_wp/heizkreis/sollspreizung_vl_rl/HEIZBETRIEB
    set_topic:  bartl_wp/heizkreis/sollspreizung_vl_rl/HEIZBETRIEB/set
    address: 28
    # description : SOLLSPREIZUNG_VL_RL_HEIZBETRIEB
    scale: 0.1
    # type: R/W
    # unit: null
  - pub_topic:  bartl_wp/heizkreis/sollspreizung_vl_rl/KUEHLBETRIEB
    set_topic:  bartl_wp/heizkreis/sollspreizung_vl_rl/KUEHLBETRIEB/set
    address: 29
    # description : SOLLSPREIZUNG_VL_RL_KUEHLBETRIEB
    scale: 0.1
    # type: R/W
    # unit: null



  - pub_topic:  bartl_wp/warmwasser/temperatur/OBEN
    address: 401
    # description: Aktuelle Warmwasser Temperatur Oben
    scale: 0.1
    # type: R
    # unit: °C
  - pub_topic:  bartl_wp/warmwasser/temperatur/STUETZTEMPERATUR
    set_topic:  bartl_wp/warmwasser/temperatur/STUETZTEMPERATUR/set
    address: 402
    # description: Warmwasser Stütztemperatur
    scale: 0.1
    # type: R/W
    # unit: °C
  - pub_topic:  bartl_wp/warmwasser/BETRIEBSART
    set_topic:  bartl_wp/warmwasser/BETRIEBSART/set
    address: 403
    # description: Betriebsart Warmwasser
    # type: R/W
    value_map:
      Aus: 0
      Auto: 1
      Ein: 2
      Einmal Laden: 3
  - pub_topic:  bartl_wp/warmwasser/temperatur/SOLLWERT
    set_topic:  bartl_wp/warmwasser/temperatur/SOLLWERT/set
    address: 404
    # description: Warmwasser Sollwert
    scale: 0.1
    # type: R/W
    # unit: °C
  - pub_topic:  bartl_wp/warmwasser/temperatur/SOLLWERT_BEI_PV_NUTZUNG
    set_topic:  bartl_wp/warmwasser/temperatur/SOLLWERT_BEI_PV_NUTZUNG/set
    address: 405
    # description: Warmwasser Sollwert bei PV_Nutzung
    scale: 0.1
    # type: R/W
    # unit: °C
  - pub_topic:  bartl_wp/warmwasser/PV_UEBERSCHUSSNUTZUNG
    set_topic:  bartl_wp/warmwasser/PV_UEBERSCHUSSNUTZUNG/set
    address: 406
    # description: PV UEberschussnutzung
    # type: R/W
    # unit: null
  - pub_topic:  bartl_wp/warmwasser/temperatur/UNTEN
    address: 407
    # description: Aktuelle Warmwasser Temperatur Unten
    scale: 0.1
    # type: R
    # unit: °C
  - pub_topic:  bartl_wp/warmwasser/ZIRKULATIONSPUMPE
    address: 408
    # description: Zirkulationspumpe
    # type: R
    # unit: null
  - pub_topic:  bartl_wp/warmwasser/temperatur/ZIRKULATIONSTEMPERATUR
    address: 409
    # description: Zirkulationstemperatur
    scale: 0.1
    # type: R
    # unit: °C
  - pub_topic:  bartl_wp/warmwasser/frischwasser/TEMPERATUR_SOLLWERT
    set_topic:  bartl_wp/warmwasser/frischwasser/TEMPERATUR_SOLLWERT/set
    address: 410
    # description: Frischwasser Sollwert
    scale: 0.1
    # type: R/W
    # unit: °C
  - pub_topic:  bartl_wp/warmwasser/frischwasser/TEMPERATUR_ISTWERT
    address: 411
    # description: Frischwasser Istwert
    scale: 0.1
    # type: R
    # unit: °C
  - pub_topic:  bartl_wp/warmwasser/frischwasser/STROEMUNGSSCHALTER
    address: 412
    # description: Strömungsschalter Frischwasser
    # type: R
    # unit: null
  - pub_topic:  bartl_wp/warmwasser/STROMVERSORGUNG_PUMPE
    address: 413
    # description: Stromversorgung Pumpe
    scale: 0.1
    # type: R
    # unit: '%'
  # - pub_topic:  bartl_wp/warmwasser/DREHZALSOLLWERT_FRISCHWASSER
  #   address: 414
  #   # description: Drehzalsollwert Frischwasser
  # #   scale: 10
  #   # type: R
  #   # unit: n/min
  # - pub_topic:  bartl_wp/warmwasser/frischwasseransteuerung/MINIMALE_DREHZAHL
  #   set_topic:  bartl_wp/warmwasser/frischwasseransteuerung/MINIMALE_DREHZAHL/set
  #   address: 415
  #   # description: Minimale Drehzahl Frischwasseransteuerung
  # #   scale: 10
  #   # type: R/W
  #   # unit: n/min
  # - pub_topic:  bartl_wp/warmwasser/frischwasseransteuerung/MAXIMALE_DREHZAHL
  #   set_topic:  bartl_wp/warmwasser/frischwasseransteuerung/MAXIMALE_DREHZAHL/set
  #   address: 416
  #   # description: Maximale Drehzahl Frischwasseransteuerung
  # #   scale: 10
  #   # type: R/W
  #   # unit: n/min



  - pub_topic:  bartl_wp/puffer/istwert/TEMTEMPERATUR_OBEN
    address: 601
    # description: Istwert Puffer Oben
    scale: 0.1
    # type: R
    # unit: °C
  - pub_topic:  bartl_wp/puffer/istwert/TEMTEMPERATUR_UNTEN
    address: 603
    # description: Istwert Puffer Unten
    scale: 0.1
    # type: R
    # unit: °C
  - pub_topic:  bartl_wp/puffer/heizen/STUETZTEMPERATUR
    set_topic:  bartl_wp/ puffer/heizen/STUETZTEMPERATUR/set
    address: 604
    # description: Stütztemperatur (Heizen) solange sich die Außentemperatur unterhalb der im Eingestellten Heizgrenze befindet
    scale: 0.1
    # type: R/W
    # unit: °C
  - pub_topic:  bartl_wp/puffer/heizen/MINIMALER_SOLLWERT_TEMTEMPERATUR
    set_topic:  bartl_wp/ puffer/heizen/MINIMALER_SOLLWERT_TEMPERATUR/set
    address: 605
    # description: Minimaler Sollwert Puffer (Heizen)
    scale: 0.1
    # type: R/W
    # unit: °C
  - pub_topic:  bartl_wp/puffer/kuehlen/MAXIMALE_TEMPERATUR
    set_topic:  bartl_wp/ puffer/kuehlen/MAXIMALE_TEMPERATUR/set
    address: 606
    # description: Maximale Puffertemperatur (Kühlen) solange sich die Außentemperatur über der im Puffer Eingestellten Kühlgrenze befindet
    scale: 0.1
    # type: R/W
    # unit: °C
  - pub_topic:  bartl_wp/puffer/SCHALTHYSTERESE_HEIZBETRIEB
    set_topic:  bartl_wp/ puffer/SCHALTHYSTERESE_HEIZBETRIEB/set
    address: 607
    # description: Schalthysterese Heizbetrieb
    scale: 0.1
    # type: R/W
    # unit: null
  - pub_topic:  bartl_wp/puffer/SCHALTHYSTERESE_KUEHLBETRIEB
    set_topic:  bartl_wp/ puffer/SCHALTHYSTERESE_KUEHLBETRIEB/set
    address: 608
    # description: Schalthysterese Kühlbetrieb
    scale: 0.1
    # type: R/W
    # unit: null
  - pub_topic:  bartl_wp/puffer/ueberschussenergie/WEITERGABE
    set_topic:  bartl_wp/ puffer/ueberschussenergie/WEITERGABE/set
    address: 609
    # description: UEberschussenergie Weitergabe
    # type: R/W
    # unit: null
  - pub_topic:  bartl_wp/puffer/ueberschussenergie/verwendung/SOLLWERT_HEIZEN
    set_topic:  bartl_wp/ puffer/ueberschussenergie/verwendung/SOLLWERT_HEIZEN/set
    address: 610
    # description: UEberschussenergie Verwendung Sollwert Heizen
    scale: 0.1
    # type: R/W
    # unit: null
  - pub_topic:  bartl_wp/puffer/ueberschussenergie/verwendung/SOLLWERT_KUEHLEN
    set_topic:  bartl_wp/ puffer/ueberschussenergie/verwendung/SOLLWERT_KUEHLEN/set
    address: 611
    # description: UEberschussenergie Verwendung Sollwert Kühlen
    scale: 0.1
    # type: R/W
    # unit: null
  - pub_topic:  bartl_wp/puffer/ueberschussenergie/VERWENDUNG
    set_topic:  bartl_wp/ puffer/ueberschussenergie/VERWENDUNG/set
    address: 612
    # description: UEberschussenergie Verwendung
    # type: R/W
    # unit: null
  - pub_topic:  bartl_wp/puffer/HEIZGRENZE_STUETZTEMPERATUR
    set_topic:  bartl_wp/ puffer/HEIZGRENZE_STUETZTEMPERATUR/set
    address: 613
    # description: Heizgrenze Stütztemperatur Puffer
    scale: 0.1
    # type: R/W
    # unit: °C
  - pub_topic:  bartl_wp/puffer/HYSTERESE_HEIZGRENZE
    set_topic:  bartl_wp/ puffer/HYSTERESE_HEIZGRENZE/set
    address: 614
    # description: Hysterese Heizgrenze
    scale: 0.1
    # type: R/W
    # unit: null
  - pub_topic:  bartl_wp/puffer/KUEHLGRENZE_STUETZTEMPERATUR
    set_topic:  bartl_wp/ puffer/KUEHLGRENZE_STUETZTEMPERATUR/set
    address: 615
    # description: Kühlgrenze Stütztemperatur Puffer
    scale: 0.1
    # type: R/W
    # unit: °C
  - pub_topic:  bartl_wp/puffer/HYSTERESE_KUEHLGRENZEGRENZE
    set_topic:  bartl_wp/ puffer/HYSTERESE_KUEHLGRENZEGRENZE/set
    address: 616
    # description: Hysterese Kühlgrenzegrenze
    scale: 0.1
    # type: R/W
    # unit: null
  - pub_topic:  bartl_wp/puffer/AKTUELLER_TEMPERATUR_SOLLWERT
    address: 617
    # description: Aktueller Puffersollwert
    scale: 0.1
    # type: R
    # unit: °C
  - pub_topic:  bartl_wp/puffer/HEIZANFORDERUNG
    set_topic:  bartl_wp/ puffer/HEIZANFORDERUNG/set
    address: 618
    # description: Heizanforderung
    # type: R
    # unit: null
  - pub_topic:  bartl_wp/puffer/KUEHLANFORDERUNG
    set_topic:  bartl_wp/ puffer/KUEHLANFORDERUNG/set
    address: 619
    # description: Kühlanforderung
    # type: R
    # unit: null
  - pub_topic:  bartl_wp/puffer/UEBERSCHUSSNUTZUNG
    set_topic:  bartl_wp/ puffer/UEBERSCHUSSNUTZUNG/set
    address: 620
    # description: UEberschussnutzung
    # type: R
    value_map:
      Aus: 0
      Heizen: 1
      Kühlen: 2



  # - pub_topic:  bartl_wp/waermepumpe/gesamt/BETRIEBSSTUNDEN_ANFORDERUNGEN
  #   address: 700
  #   # description: Betriebsstunden der gesamten Anforderungen
  # #   # type: R
  #   # unit: h_DE
  - pub_topic:  bartl_wp/waermepumpe/gesamt/ELEKTRISCHER_VERBRAUCH_KWH
    address: 702
    # description: Gesamt Elektrischerverbrauch
    scale: 2.7777778E-07
    # scale: 3.6E+06
    # type: R
    # unit: kWh
  - pub_topic:  bartl_wp/waermepumpe/gesamt/ERZEUGTE_WAERMEENERGIE_KWH
    address: 703
    # description: Gesamt Erzeugte Wärmeenergie
    scale: 2.7777778E-07
    # scale: 3.6E+06
    # type: R
    # unit: kWh
  - pub_topic:  bartl_wp/waermepumpe/STATUS
    set_topic:  bartl_wp/ waermepumpe/STATUS/set
    address: 704
    # description: Status der Wärmepumpe
    # type: R
    value_map:
      Standby: 0
      Vorlauf: 1
      Heizbetrieb: 2
      Abtaubetrieb: 3
      Kühlbetrieb: 4
      Nachlauf: 5
      Sicherheitsabschaltung: 7
      Störung: 8
  - pub_topic:  bartl_wp/waermepumpe/MESSAGE_ID_OF_THE_FLOW_TEMPERATURESENSOR
    address: 705
    # description: Message ID of the flow temperaturesensor
    # type: R
    # unit: null
  - pub_topic:  bartl_wp/waermepumpe/temperatur/VORLAUF
    address: 706
    # description: Aktueller Wärmepumpen Vorlauf
    scale: 0.1
    # type: R
    # unit: °C
  - pub_topic:  bartl_wp/waermepumpe/temperatur/QUELLEN_EINTRITT
    address: 707
    # description: Aktueller Wärmepumpen Quellen Eintritt
    scale: 0.001 # looks wrong
    # type: R
    # unit: °C
  - pub_topic:  bartl_wp/waermepumpe/temperatur/QUELLEN_AUSTRITT
    address: 708
    # description: Aktueller Wärmepumpen Quellen Austritt
    scale: 0.001
    # type: R
    # unit: °C
  - pub_topic:  bartl_wp/waermepumpe/temperatur/RUECKLAUF
    address: 709
    # description: Aktueller Wärmepumpen Rücklauf
    scale: 0.1
    # type: R
    # unit: °C
  - pub_topic:  bartl_wp/waermepumpe/temperatur/KAELTEMITTEL_HEISGAS
    address: 710
    # description: Kältemittel Heisgastemperatur
    scale: 0.1
    # type: R
    # unit: °C
  - pub_topic:  bartl_wp/waermepumpe/LUEFTER_DREHZAHL
    address: 711
    # description: WQP_Luft WP_Lüfter Drehzahl/Bei Sole/Wasser die Versorgung der Quellenpumpe (100%=An)
    # type: R
    # unit: '%'
  - pub_topic:  bartl_wp/waermepumpe/STROMVERSORGUNG_WAERMEERZEUGERPUMPE_PROZENT
    address: 712
    # description: Stromversorgung Wärmeerzeugerpumpe (100%=An)
    # type: R
    # unit: '%'
  - pub_topic:  bartl_wp/waermepumpe/tandem_wp/STATUS_VERDICHTER_STUFE1
    address: 713
    # description: Bei Tandem WP_Status der Verdichter Stufe 1
    # type: R
    # unit: null
  - pub_topic:  bartl_wp/waermepumpe/tandem_wp/STATUS_VERDICHTER_STUFE2
    address: 714
    # description: Bei Tandem WP_Status der Verdichter Stufe 2
    # type: R
    # unit: null
  - pub_topic:  bartl_wp/waermepumpe/sicherheitskette/HOCHDRUCK
    address: 715
    # description: Sicherheitskette Hochdruck
    # type: R
    # unit: null
  - pub_topic:  bartl_wp/waermepumpe/sicherheitskette/NIEDERDRUCK
    address: 716
    # description: Sicherheitskette Niederdruck
    # type: R
    # unit: null
  - pub_topic:  bartl_wp/waermepumpe/sicherheitskette/QUELLEN_FEHLER
    address: 717
    # description: Sicherheitskette Quellenfehler
    # type: R
    # unit: null
  - pub_topic:  bartl_wp/waermepumpe/sicherheitskette/VERDICHTER_MOTORSCHUTZ
    address: 718
    # description: Sicherheitskette Verdichter Motorschutz
    # type: R
    # unit: null
  - pub_topic:  bartl_wp/waermepumpe/betriebsstunden/VERDICHTER1
    address: 719
    # description: Betriebsstunden Verdichter 1
    # type: R
    # unit: null
  - pub_topic:  bartl_wp/waermepumpe/betriebsstunden/VERDICHTER 2
    address: 720
    # description: Betriebsstunden Verdichter 2
    # type: R
    # unit: null
